pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

include 'editor'
include 'loader-libgdx-common'
include 'loader-libgdx-box2d-v1.12.1'
//include 'loader-libgdx-box2d-v3.1.1'
include 'loader-libgdx-demo'
