plugins {
    id 'application'
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"

    implementation files('./libs/tween-engine-api.jar')

    implementation project(':loader-libgdx:box2d-v1.12.1')

}

application {
    mainClass = 'aurelienribon.bodyeditor.Main'
}
