plugins {
    id 'application'
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl:1.12.1"
    implementation "com.badlogicgames.gdx:gdx-box2d-platform:1.12.1:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-platform:1.12.1:natives-desktop"

    implementation project(":lib:box2d-editor:libs:tween-engine-api")

    implementation project(':lib:box2d-editor:loader:box2d-v1.12.1')

}

application {
    mainClass = 'aurelienribon.bodyeditor.Main'
}
