plugins {
    id 'application'
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"

    implementation "net.java.balloontip:balloontip:1.2.1"
    implementation "commons-io:commons-io:2.1"
    implementation "org.json:json:20090211"

    implementation files('./libs/css-engine-swing-api.jar')
    implementation files('./libs/tween-engine-api.jar')

}

application {
    mainClass = 'aurelienribon.bodyeditor.ui.Main'
}
